### ISSUE TITLE
InputList impossible to read

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1047]
I raised this issue some time ago and I can't really remember how it ended, but compared to `GenericParameters`, which had a nice representation, `InputList` is very difficult to read. One way to make it more readable is to put `print(job.input.to_sphinx())`, but just to take a look at the content, it's too much work. Can we make it look better just with executing `job.input`?

**Comment by pmrv** [comment]
The problem is that the tree view is collapsed by default?  As of now the InputList uses the default way of how jupyter displays json, maybe there's an option to unfold the first few layers by default.  If not I could override __str__ with a [pretty printer](https://docs.python.org/3/library/pprint.html?highlight=pprint#module-pprint) as a quick fix.  I think mid- to long-term it'd be nice to have an interactive tree view for the lists as @JNmpi show cased in a few pyiron meetings now, but that's a time issue.

**Comment by jan-janssen** [comment]
Same here @samwaseda and @pmrv What is the status of this issue? Is it solved?

**Comment by samwaseda** [comment]
From last week's pyiron meeting I understand that it works fine with Jupyter Lab, although because of a few snippets which are either missing or I don't know how to activate, I personally haven't switched to Jupyter Lab yet.
