### ISSUE TITLE
InputList unexpected behaviour

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1053]
I realized that `False` was translated to 0 during the conversion (or `True` to 1)

```
>>> art = pr.create_job('ActivationRelaxationTechnique', 'art')
>>> art.input.art_id = art_id
>>> art.input.direction = direction
>>> art.input.fix_layer = False
>>> minim = pr.create_job('SxExtOptInteractive', 'sxextopt')
>>> minim.ref_job = art
>>> minim.save()
>>> minim = pr.load('sxextopt')
>>> print(minim.ref_job.input.fix_layer)
0
```

But the weird thing is, it doesn't happen when the other terms are not defined, like here:
```
>>> art = pr.create_job('ActivationRelaxationTechnique', 'art')
>>> # art.input.art_id = art_id
>>> # art.input.direction = direction
>>> art.input.fix_layer = False
>>> minim = pr.create_job('SxExtOptInteractive', 'sxextopt')
>>> minim.ref_job = art
>>> minim.save()
>>> minim = pr.load('sxextopt')
>>> print(minim.ref_job.input.fix_layer)
False
```

Since `fix_layer` is only used for `if ... else` in `activation_relaxation_technique.py`, I guess it comes from `InputList`? Sorry I used here a module which hasn't been merged yet.

**Comment by jan-janssen** [comment]
@samwaseda and @pmrv What is the status of this issue? Is it solved?

**Comment by pmrv** [comment]
Haven't looked into this yet, but it seems that it is related to the HDF5 serialization.  I won't have time until next week, but I would assume this might be fixed when I rework that part of the code (as discussed in the last pyiron meeting, but no progress since then).

**Comment by pmrv** [comment]
I've looked again into this and it seems to be a general issue with out HDF implementation.  Assigning booleans to a value in a ProjectHDFio coerces to int.
```python
from pyiron_base import Project
pr = Project('test')
h = pr.create_hdf(pr.path, 'test')
h['foo'] = False
h['foo']
>>> 0
```
This also explains why you don't see the behavior when the other values are presents, in this case the whole list is saved as json, so our HDF implementation never sees the boolean.  I suggest to close the issue for now, because I don't see an easy fix without rewrittng HDF and it doesn't seem critical, just odd.
