### ISSUE TITLE
Pressure setting in LAMMPS MD fails with "None" entries in list

### ISSUE THREAD

**Issue by t-brink** [pyiron/pyiron#1074]
I set up a LAMMPS job like this:

```
job = pr.create_job(pr.job_type.Lammps, "test1")
job.structure = ...
job.potential = ...
job.calc_md(
    temperature=1000.0,
    temperature_damping_timescale=100.0,
    pressure=[0.0, 0.0, 0.0, None, None, None], # <-------------------
    pressure_damping_timescale=500.0,
    time_step=1.0,
    n_ionic_steps=100000,
)
```

In the `control.inp` file this is erroneously translated to the following fix:

```
fix ensemble all npt temp 1000.0 1000.0 0.1 x 0.0 0.0 0.5 y 0.0 0.0 0.5 z 0.0 0.0 0.5 xy nan nan 0.5 xz nan nan 0.5 yz nan nan 0.5
```

while it should omit the `xy`, `xz`, and `yz` components.

I tried with the newest git version from the main branch.

**Comment by t-brink** [comment]
I dug into this and the problem is that `pyiron.lammps.control.LammpsControl.pressure_to_lammps()` contains the following conversion from the pressure input list:

```
pressure = np.array(all_pressures, dtype=float)
```

The `dtype=float` will convert all `None`s to `nan`s and in `pyiron.lammps.control.LammpsControl.calc_md()` in [line 516](https://github.com/pyiron/pyiron/blob/595bbc0a53ab1e841e826142e4fcbc2e3bc6691d/pyiron/lammps/control.py#L516), there is a check `if value is not None:`, which will evaluate to `True` for `nan`. The same might be true for `calc_minimize()`, but I didn't encounter this, yet. Probably `pressure_to_lammps()` needs to return a list with the `None` values intact? Needs careful checking how that interacts with the rotation, so I hesitate to provide a naive patch.

**Comment by pmrv** [comment]
Relevant previous commits:
https://github.com/pyiron/pyiron/commit/f95e3b086262c470520123cdad0f144f9843b97d
https://github.com/pyiron/pyiron/commit/75f1bc9455b3cb96e9db569dae35324094777c0a

**Comment by liamhuber** [comment]
I think @samwaseda is our rotations master?

**Comment by t-brink** [comment]
I discusses with @pmrv and I will propose a pull request soon. It seems trivial to fix without disturbing anything.

**Comment by samwaseda** [comment]
Actually I thought about fixing the issue quickly, but then realized the complexity of the underlying problem and didn't start working on it...

One question that should be answered is, do we support the Voigt notation? If yes, the implication is that the strain tensor is probably also given in a symmetric matrix, which then requires a structure rotation for LAMMPS, which in the end forbids the usage of `None` as @t-brink is using it, because the definition of the axes will change and therefore you cannot define hydrostatic components and shear components independently anymore. One workaround would be to use an upper triangle matrix for the strain tensor, but then it looks extremely incompatible with the Voigt notation...

**Comment by t-brink** [comment]
The strain does not have to be symmetric if you also include a rotation in it to keep the simulation cell vectors aligned with the LAMMPS requirements; this has nothing to do with Voigt notation or not. This is not very clean, but works for us MD people, especially in the small strain approximation.

The present code forbids using `None` when the box has to be rotated for LAMMPS. If we leave this in, the fix is easy and this is what we should do to make it usable _right now_. It would also fit with the typical use cases of MD users, who are used to this after all.

Later on, it might be nice to be able to apply stresses only in some direction on _any_ input structure, but I would say this is a separate issue, which should not block a bugfix here.

**Comment by samwaseda** [comment]
> The strain does not have to be symmetric if you also include a rotation in it to keep the simulation cell vectors aligned with the LAMMPS requirements

That's what I'm saying. And that's exactly what's extremely counter intuitive to me, i.e. the pressure is given in the Voigt notation, but the strain tensor is not symmetric.

> this has nothing to do with Voigt notation or not.

No that's not true. At least I've never heard of Voigt notation for a non-symmetric pressure/strain.

This being said, I have also never heard of the case where the strain tensor is not symmetric, because in most of the textbooks in linear elasticity, the strain tensors are **by definition** symmetric, although at least in the case of strain tensor, most of the textbooks also state that it's possible to define a non-symmetric strain tensor.

> 
> Later on, it might be nice to be able to apply stresses only in some direction on _any_ input structure, but I would say this is a separate issue, which should not block a bugfix here.

Following this statement, I guess the best option is to forbid all anisotropic pressure, i.e. we allow only the global pressure. Because at least this way, we can be sure that the results are correct, and the user knows what's possible and what's not. What do you think?

**Comment by liamhuber** [comment]
**Please be extremely careful.** You say in the OP

> it should omit the `xy`, `xz`, and `yz` components.

I'm not saying here that you're wrong about that. But I am also not convinced that you are right.

While I'm writing this Sam also replied, but I want to expand a bit on something he mentioned in his previous comment that may not have been fully appreciated:

The pyiron cell vectors are (completely?) arbitrary, but for use in Lammps we need to usually (always?) rotate the cell until it's in an upper triangular format. From my understanding, that means if your pyiron cell has [a, b, c, None, None, None] pressure it does not follow that your Lammps cell has [a', b', c', None, None, None] pressure!

Please also remember that during your tests zero-pressure conditions are not sufficient as rotating zero still gives zero.

I have to confess that I myself do not a have a full understanding of this issue. Some possible pressures *intentionally* do not run a simulation because we're not currently confident it would be the *right* simulation. I simply beg you to please please please be extremely cautious and self-doubting when playing around with this part of the code base.

**Comment by t-brink** [comment]
@liamhuber : It has been fully appreciated. If there is rotation and a `None` entry, an exception is raised because the definition is unclear. That remains as-is for now and I support this fully. **But**, if the cell matches the input expected by LAMMPS, everything is just fine.

@samwaseda : Yes, things are a bit weird with the Voigt notation and I wish LAMMPS supported arbitrary boxes, but here we are. What I find a bit confusing is that you are putting stress and strain in the same box. If you have a non-symmetric "strain tensor", what you are doing is applying a strain and a rotation. The stress tensor will remain symmetric. That's what I don't get about your objection, or am I wrong about something here?

I beg you all to please, please, please remember that LAMMPS users have dealt with that for a while and that non-hydrostatic pressures are an essential feature. Pull request will follow in a few seconds, maybe it is more productive to discuss actual changes.

**Comment by samwaseda** [comment]
> If you have a non-symmetric "strain tensor", what you are doing is applying a strain and a rotation. The stress tensor will remain symmetric.

Ok this is true, I'm sorry for my remark

> I beg you all to please, please, please remember that LAMMPS users have dealt with that for a while and that non-hydrostatic pressures are an essential feature. Pull request will follow in a few seconds, maybe it is more productive to discuss actual changes.

Yeah I know it painfully - it's just it's not a LAMMPS problem but it's a pyiron problem. but ok I agree that we can continue the discussion in the PR.

**Comment by liamhuber** [comment]
>  it's just it's not a LAMMPS problem but it's a pyiron problem. 

+1. My concern is on the pyiron side, and the fact that the pyiron implementation for the interface is not always transparent.
