### ISSUE TITLE
Vasp: Inconsistency - output/electronic_structure/occ_matrix vs. output/electronic_structure/occupancy_matrix

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#112]
@sudarsan-surendralal I noticed that VASP sometimes uses: 
`job['output/electronic_structure/occ_matrix']` 
and also:
`job['output/electronic_structure/occupancy_matrix']` 
can you take a look at this?

**Comment by jan-janssen** [comment]
I guess the same is true for `job['output/electronic_structure/eigenvalue_matrix']` and `job['output/electronic_structure/eig_matrix']`.

**Comment by sudarsan-surendralal** [comment]
If I remember correctly, I think it was Joerg who suggested `occ_matrix` and `eig_matrix` instead of `occupancy_matrix` and `occ_matrix`. So I changes it here https://github.com/pyiron/pyiron/commit/ff1af7c3899cd498030996416662ca3c811fdd6e#diff-8cf87eb8d1d2e2b7bc2be49ba79c6dc7 (the new to_hdf() and from_hdf() has the new names). So I think the inconsistency is with jobs done before this commit was made. If you are loading the object, it shouldn't matter!

**Comment by jan-janssen** [comment]
Ok, I had a project with calculations from the 7th of January and the 13th and those were not consistent. Maybe the next time we should have a certain level of backwards compatibility - in this case we could have written both.
