### ISSUE TITLE
Make pyiron more self-explanatory

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1284]
pyiron is developed by different people and we all have different standards - some people prefer to make example notebooks and others prefer to make more elaborate doc strings. In my opinion, we can behold the great principle that we only need to import `Project` to do an entire research and we should also stick to it when it comes to documentation. In particular, I would like to make separate documentations as redundant as possible (because it's super cumbersome to look for the appropriate notebooks and understand which cells are what I need). To this end, I would like to suggest the following points when we implement new job types:

- The class level doc string should contain (1) what it does and (2) a short example.
- All relevant methods are mentioned in the class level doc string or they start with `get_` or `set_`.
- All other methods should be private methods.
- Capture physically senseless setups (however stupid they may appear) early and raise meaningful errors (so that errors are also educational).

Furthermore, I personally pay attention to the following points, but I don't require others to do the same:

- Explain what kind problems one may expect for setting too large/small values in the method doc strings (e.g. strain rate for Murnaghan).
- Explain in method doc strings which other methods are related (e.g. `set_convergence_precision` and `calc_minimize` etc.).

Of course, these are the things that came to **my** mind, so feel free to agree or disagree. I'm open to more suggestions so let me know what you think. By the way, the [elastic class](https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/master/elastic.py) that I uploaded recently very much follows the points I mentioned above, meaning as much as I can imagine, all you have to do is load the class and you shouldn't need a separate example notebook to understand what it does.

**Comment by jan-janssen** [comment]
I agree with most of the points, apart from the private functions. The issue with the private functions is that Python suggests to use private functions for functionality within one object and public functions to connect different objects. Now we have a third level which is the user interacting with these objects and I do not see a clear strategy yet how to handle these three levels. My only suggestion would be to again use decorators to high internal functions from the user.

**Comment by pmrv** [comment]
What about the following guide lines for private functions:
- If we expect users to call them, they get a plain name `do_whatever()`
- if we expect developers or other classes to call them, they get an underscore `_do_a_dev_thing()` (this is what we do already)
- everything else that will just be called from the class on itself, gets the python name mangeling leading double underscore `__do_the_plumbing()`.

**Comment by liamhuber** [comment]
@samwaseda I like this idea. In general I would also push the general principle that docstrings should focus as much as possible on *why* the code exists, rather than *how* the code operates (which should, hopefully, be obvious from the code itself). With that said, I'm definitely not 100% against some "how", for instance giving a little operational example in each class sounds great.

> All relevant methods are mentioned in the class level doc string or they start with get_ or set_.

I would push back against this. The methods should be visible from tab completion, should be described in their own docstring, and should be well-named enough that it's clear whether or not I want to know more about them from the name alone. Actually talking about them in the class-level docstring will lead to duplication IMO.

If you replaced "methods" with "public attributes", then I'm 100% behind having these described at the class level. Most jobs don't have their own new attributes (i.e. all are inherited), but I think describing the `input` and `output` fields might be worthwhile.

> The issue with the private functions is that Python suggests to use private functions for functionality within one object and public functions to connect different objects. -@jan-janssen 

> if we expect developers or other classes to call them, they get an underscore _do_a_dev_thing() (this is what we do already) -@pmrv 

I disagree with Marvin and agree with Jan. More generally than Jan, I would say that private functions/methods/variables are only expected to be accessed from within their own *scope*. I.e. an entire module can be private, as long as it's only accessed by sister modules; within a module a public class can instantiate a private class from the same module; a method inside a class can call a private method from the same class but not a private method of another class; etc. In pyiron we seem to obey this fairly well, and indeed sometimes make things public that *don't* need to be public!

> I do not see a clear strategy yet how to handle these three levels -@jan-janssen 

I agree. I think the orthodox solution is to really have public facing interface classes that only expose the public-public methods, and have these classes appear in the creation menus (or `__init__`), and under the hood they instantiate to a private variable the actual business classes which follow the regular python conventions for public and private. We've talked about this before an it gets the job done without violating any rules or messing around with `__dir__` for tab-completion, but it also feels bloated. Honestly, maybe we need to bite the bullet and do this sort of separation of our UI and business logic, but I'm just not ready to commit to that yet.

**Comment by samwaseda** [comment]
> I do not see a clear strategy yet how to handle these three levels

Hm ok then let's stick to the python principle. I'm also okay with @pmrv's solution, but this kind of decision probably follows democracy and with two of you against it, I'm not going to initiate an interpyironic war.

>> All relevant methods are mentioned in the class level doc string or they start with get_ or set_.

> I would push back against this. The methods should be visible from tab completion, should be described in their own docstring, and should be well-named enough that it's clear whether or not I want to know more about them from the name alone. Actually talking about them in the class-level docstring will lead to duplication IMO.

> If you replaced "methods" with "public attributes", then I'm 100% behind having these described at the class level. Most jobs don't have their own new attributes (i.e. all are inherited), but I think describing the input and output fields might be worthwhile.

I guess the distinction is between inherited and not inherited, and not between methods and public attributes, right? If you mean "a class's own new methods/attributes should be described in the class level", then I totally agree. For example in the case of phonopy (btw. this is the class that made me start writing this whole issue in the first place), there's [`get_thermal_properties()`](https://github.com/pyiron/pyiron_atomistics/blob/89cee774eed36888bc28425bc423a2135ef979f9/pyiron_atomistics/atomistics/master/phonopy.py#L313), which is a method and is very much the core of this class (along with a few other `get_` functions which give you similar information from different angles). This one must be either clearly visible in the tab completion list or stated in the class level doc string (preferably both).

**Comment by liamhuber** [comment]
> This one must be either clearly visible in the tab completion list or stated in the class level doc string (preferably both).

@samwaseda I think the only thing we disagree on is whether methods should appear in the class docstring *at all*. I think that as a rule of thumb they shouldn't. The [sphinx google docstring example](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) clearly omits method descriptions, while the [numpy styleguide](https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring) points out they don't *need* to be there, but *can* be if the class has many methods of which you want to highlight only a few.

Every time we make the users life easier by writing method descriptions at the class level, we make the developer's life harder by doubling the amount of documentation to maintain for that method -- potentially making the user's life *much* worse if we fail to update part of the documentation! 

I'm ok with the numpy approach: do it if it's super necessary, but let's first try to get the job done with good naming and well organized tab-completion menus.

**Comment by samwaseda** [comment]
Thank you for all the comments and the discussion at today's pyiron meeting!
