### ISSUE TITLE
ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'pyrion/dev'

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1355]
**I encountered the error: "ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'pyrion/dev'" when I log in the cmti cluster using "ssh -x -L 30000:localhost:30000 username@cmti001.bc.rzg.mpg.de"**

 

Apparently, it should be "**pyiron**/dev" but not "**pyrion**/dev". I don't know what triggered this error and how to fix it.  I currently also cannot connect the JupyterHub. It complains "Safari can't establish a secure connection to the server 'localhost'". But it worked well yesterday evening. I wonder these two issues are connected.

Any hint/suggestion would be very helpful.

Thank you very much in advance.

**Comment by muh-hassani** [comment]
The module is loaded in your `.bashrc` file, how this has been changed, I don't know. Unfortunately, you are the only one who can access and modify the file in your home directory. Maybe you can create a ticket in mpcdf help desk, they might be able to help you. The link to the help desk: https://helpdesk.mpcdf.mpg.de/mpcdf/index.html

P.S., I removed the bug label, since it is not a bug of pyiron code.

**Comment by lfzhu-phys** [comment]
@muh-hassani  I have checked my .bashrc file before I open this issue. Everything was ok. Anyhow, I just tried to log in the cluster. The error message is still there, but the JupyterHub works now. Thanks for your reply.
