### ISSUE TITLE
time out of jobs after 4 days 

### ISSUE THREAD

**Issue by mostafajoulaian** [pyiron/pyiron#1402]
**Summary**

Dear All 
I am trying to do Sphinx Calculation but during convergence my job get aborted due to the time out ( which basically is  time limit for pyiron ) 

**Detailed Description**

I would like to ask is there anyway that I could extend time limitation for jobs .
secondly I wanted to ask to see is there any future in pyiron that let me re-run my aborted job and pick up from the last energy stage instead of re-run job from beginning?

**Further Information, Files, and Links**

**Comment by jan-janssen** [comment]
I remember that @sudarsan-surendralal had the permission to execute long term jobs beyond the run time limit of the queuing system. So either talk to him or just email @freyso about it.

**Comment by samwaseda** [comment]
As @sudarsan-surendralal points out, pyiron wouldn't be able to store the output if the job is killed. In order to restart the calculation with SPHInX, you can manually collect the output and launch a new job via:

```python
pr = Project('my_project')
job = pr.load('my_job')
job.collect_output()
new_job = job.restart()
new_job.run()
```

**Comment by freyso** [comment]
The max time for small jobs (s.cmfe, <= 40 cores) is currently 7 days.
Otherwise, for the job restart  option of Sam, you may need to repeat the direct settings of SPHInX input, because I don't think these are visible to the restart function.

**Comment by samwaseda** [comment]
> Otherwise, for the job restart option of Sam, you may need to repeat the direct settings of SPHInX input, because I don't think these are visible to the restart function.

What do you mean by that?

**Comment by freyso** [comment]
Things like
job.input[".../scfDiag/preconditioner/"].type = "ELLIPTIC";

**Comment by samwaseda** [comment]
> Things like
> `job.input[".../scfDiag/preconditioner/"].type = "ELLIPTIC";`

This kind of stuff should be copied. If not, open a new issue.

**Comment by freyso** [comment]
never tried that myself, just heard rumors from my group that restarting doesn't work properly, and I assumed it happens if we manipulate the sphinx input tree directly. 
Maybe I explained badly - we first generate the SPHInX input tree from the generic input, and then start manipulating (and it actually may be input.sphinx[...].
I wouldn't see how it could work conceptually, because you don't have tree diff algorithms as far as I can tell to capture our postprocessing changes, or to apply the necessary changes for restarting to the rolled-out input.
Anyway, one should probably test what happens.

**Comment by samwaseda** [comment]
> Anyway, one should probably test what happens.

👍

**Comment by jan-janssen** [comment]
As the issue is inactive for over a month I close it now.
