### ISSUE TITLE
Documentation or Feature for Environment Use on Remote

### ISSUE THREAD

**Issue by pstaerk** [pyiron/pyiron#1461]
**Summary**
I had set up pyiron inside of a conda environment on a remote HPC cluster (mostly because installing pyiron in base is extremely slow) and realized that while working flawlessly inside of the environment, there seems to be no way for me to run jobs externally on the HPC when using the remote option for queuing jobs.

**Detailed Description**
Is there a way of specifying a remote environment in the configuration and it is not documented (or I did not find it)?
Is it possible to specify the environment in the config? Using environments would be really advantageous for testing different versions etc.

**Comment by niklassiemer** [comment]
Hi @pstaerk,

 I am not 100% sure I got your setup correctly. You did install pyiron on an HPC and want to run there? Then you would not need the so called remote setup of the queuing system, but only the queueing itself (remote is for working at your laptop and sending stuff to another HPC - which also could be your setup...)

In either case, it is sadly not possible right now to specify a the environment in which the remote pyiron should be executed. The python process determining this is always started first (and thus would be in the standard login environment). (In addition to conda, there could also be several different other environmental variables be changing, like e.g. `module load intel/2019` or the like to be considered). If it would not harm otherwise, you may alter your login script (e.g. `.bashrc`) to load the correct environment for pyiron from the beginning. In that case, all features should work like expected.

If you 'only' want to send specific jobs with external executables to the (HPC local) queuing system, you can alter the run scripts in the pyiron resources to load a specific environment before starting the actual calculation.

**Comment by pstaerk** [comment]
I have a work-machine from which i submit jobs over ssh to a HPC slurm queue. And I installed pyiron via the usual `conda install -c conda_forge pyiron` command, however not in the base environment but into a conda environment. I will try to change the bashrc as you have suggested, sounds like a good idea!

**Comment by pmrv** [comment]
Just for completeness:  another point of injecting this would be via the queuing script defined for the queue adapter.  You could do this already now by changing the script that is in the `queues` folder of your pyiron resources.  Midterm, it might be nice to add this to `pysqa`, similar as requested [here](https://github.com/pyiron/pyiron_base/issues/1045).
