### ISSUE TITLE
Inconsistent behavior of positions and scaled_positions

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron#598]
Adding something to scaled positions does nothing when applying a filter condition,
see the below example

```
from pyiron import Project
Al = pr.create_ase_bulk("Al", cubic=True)
Al.set_repeat((1,1,6))
z = Al.scaled_positions[:,2]

print("Attempt to add something to scaled positions")
print(Al.scaled_positions[z<1, 0])
Al.scaled_positions[z<0.5, 0] += 0.2
print(Al.scaled_positions[z<1, 0])
print()
print("Add something to positions applying the same filter condition works")
print(Al.scaled_positions[z<1, 0])
Al.positions[z<0.5, 0] += 0.2
print(Al.scaled_positions[z<1, 0])
print()
print("Adding something to scaled positions without filter condition also works")
Al.scaled_positions += 0.2
print(Al.scaled_positions[z<1, 0])
print()
print("Adding something to only the x coordinate also works when using a tuple")
Al.scaled_positions += (0.2,0,0)
print(Al.scaled_positions[z<1])
print()
print("But it does nothing when using the filter condition")
# the filter condition is acutally copied and not a reference, so it has to be renewed
z = Al.scaled_positions[:,2]
Al.scaled_positions[z<0.5] += (0.2,0,0)
print(Al.scaled_positions[z<1])
```

**Comment by jan-janssen** [comment]
Hi @Leimeroth 

That is correct ... the issue is that the property getter returns a numpy array and when something is set to the numpy array, it is calling the getter rather than the getter, so we can not handle it. 

@samwaseda  is already working on this issue. 

Our recommendation is to either user positions, or `get_scaled_postitions()` and `set_scaled_positions()`: 

- https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L1111
- https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L3545

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pyiron/pull/599

**Comment by samwaseda** [comment]
From [this pull request](https://github.com/pyiron/pyiron/pull/599) on, you will see an explicit warning whenever you call `scaled_positions`.

**Comment by jan-janssen** [comment]
The issue has been inactive for 14 days, so I close it for now.
