### ISSUE TITLE
set_kpoints for specific DFT modules

### ISSUE THREAD

**Issue by ashtonmv** [pyiron/pyiron#612]
@sudarsan-surendralal Can you comment on this? I though that the codes should implement the `_set_kpoints` function while `set_kpoints` is only defined in `GenericDFT`.

_Originally posted by @jan-janssen in https://github.com/pyiron/pyiron/pull/592_

**Comment by jan-janssen** [comment]
@ashtonmv sorry - I already created an issue for this https://github.com/pyiron/pyiron/issues/610 so we can close this one.

**Comment by sudarsan-surendralal** [comment]
@jan-janssen, since this is a more specific issue with inheritance and not about decorators let's discuss this here.

The idea to have `set_kpoints` (or any function) defined in `GenericDFTJob` which calls `_set_kpoints` from the derived class seems good. However, if the user looks up the docstrings of the `set_kpoints` function, it returns the base class docstring. But what if you have additional options in some codes (eg. VASP  has the "Gamma" scheme while SPHINX doesn't) and you need it to be included in the docstrings as well? Wouldn't it be better to implement them in the derived class then?

**Comment by jan-janssen** [comment]
@sudarsan-surendralal Do we need to change anything here? Or can we close the issue for now.
