### ISSUE TITLE
Phonopy - get_thermal_properties() - Deprecation warnings

### ISSUE THREAD

**Issue by prince-mathews** [pyiron/pyiron#691]
To extract free energies from Phonopy jobs, I use:
`therm = phon.get_thermal_properties(temperatures=pes.temperatures)`

Each time this function executes, the following 2 warnings pop up:
> /u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/phonopy/api_phonopy.py:2122: DeprecationWarning: Phonopy.set_thermal_properties is deprecated. Use Phonopy.run_thermal_properties
>   DeprecationWarning)
> /u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/phonopy/api_phonopy.py:2165: DeprecationWarning: Phonopy.get_thermal_properties is deprecated. Use Phonopy.get_thermal_properties_dict.
>   DeprecationWarning)

I checked the repositories on gitlab and github, on Gitlab, under the function `get_thermal_properties()` I see the functions `set_thermal_properties()` and `phonopy.get_thermal_properties()` , while on the Github repository, I see `run_thermal_properties()` and `phonopy.get_thermal_properties_dict()`.

How do I avoid these warnings?

**Comment by jan-janssen** [comment]
The issue was fixed in https://github.com/pyiron/pyiron/pull/647/ - It seems like you are using pyiron 0.2.14 which does not include this fix yet: https://github.com/pyiron/pyiron/blob/pyiron-0.2.14/pyiron/atomistics/master/phonopy.py#L309 

To check which version of pyiron you are using, you can use: 
```
import pyiron
pyiron.__version__
```

I just triggered the release of pyiron 0.2.15, so it is going to be available on the cluster in Garching early next week. https://github.com/pyiron/pyiron/releases

**Comment by prince-mathews** [comment]
The version I am using is 0.2.14.

Thank you!
