### ISSUE TITLE
Shouldn't submitted notebook be compressed?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#742]
I have two notebooks:

Notebook I:
```
job = Project('SUBMIT').create_job('ScriptJob', 'script')
job.script_path = 'simulation.ipynb'
... job creation ...
job.run()
```

Notebook II (simulation.ipynb):
```
job = Project('SIMULATION').create_job('Lammps', 'job')
... job creation ...
job.run()
```

I realized that the files in the job `job` are compressed, but the ones in `script` aren't. Shouldn't they be compressed as well?

**Comment by jan-janssen** [comment]
I guess the reason why we do not compress the files in a script job is that we want to be able to analyse the calculations from another project. For example when the script job is creating the calculations and a separate notebook is used for analysis.

**Comment by samwaseda** [comment]
Ok but then shouldn't there be a possibility of compressing the files for the user? I just tried it but then it complained that the project folder (in the example above, that would be `SIMULATION`) is not empty.

**Comment by jan-janssen** [comment]
You could implement a more extensive compression function inside the script job. Currently it is using the default function https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/core.py#L907 . Still the issue is that it does not make sense to compress already compressed files. So basically you would have to extract all compressed files and then compress them again.
