### ISSUE TITLE
View structure along an axis using plot3d() 

### ISSUE THREAD

**Issue by raynol-dsouza** [pyiron/pyiron#762]
I think it would be helpful (sometimes) to be able to view structures/surfaces from plot3d() along an axis, than to have to manually rotate it. @samwaseda could you maybe look into adding this feature to plot3d()?

**Comment by samwaseda** [comment]
Sorry I still haven't found time but I'll surely take on this one

**Comment by samwaseda** [comment]
ok this one turned out to be a bit trickier than I thought. I must be somehow related to [this function](https://github.com/arose/nglview/blob/e3b1bb0faf32be689ac4901469d9da721fb90863/nglview/viewer_control.py#L58) but I haven't really figured out how the orientation is given by a 16-dim (4-dim) array.

**Comment by pmrv** [comment]
My lucky guess are [quaternions](https://en.wikipedia.org/wiki/Quaternion#Matrix_representations).  Maybe [this](https://github.com/arose/nglview/issues/596) old issue gives a clue where to look. I just skimmed it though. :|

**Comment by ashtonmv** [comment]
Maybe I can help, since I had spent some time playing with this before. That flattened 4x4 matrix is just an affine spatial transformation (rotation + scaling + translation), like what they describe [here](https://www.brainvoyager.com/bv/doc/UsersGuide/CoordsAndTransforms/SpatialTransformationMatrices.html). The code below is basically what I have previously used to achieve API-based orientations.

```python
import numpy as np
import pyiron
```
```python
structure = pyiron.create_structure("Fe", "bcc", lattice_constant=2.87)
```
```python
# Just a helper function
def get_rotation_matrix(axis, theta):
    """
    Find the rotation matrix associated with counterclockwise rotation
    about the given axis by theta radians.
    Credit: http://stackoverflow.com/users/190597/unutbu
    Args:
        axis (list): rotation axis of the form [x, y, z]
        theta (float): rotational angle in radians
    Returns:
        array. 4x4 affine Rotation matrix (no translation).
    """

    axis = np.array(list(axis))
    axis = axis / np.linalg.norm(axis)
    axis *= -np.sin(theta/2.0)
    a = np.cos(theta/2.0)
    b, c, d = tuple(axis.tolist())
    aa, bb, cc, dd = a*a, b*b, c*c, d*d
    bc, ad, ac, ab, bd, cd = b*c, a*d, a*c, a*b, b*d, c*d
    return np.array([[aa+bb-cc-dd, 2*(bc+ad), 2*(bd-ac), 0],
                     [2*(bc-ad), aa+cc-bb-dd, 2*(cd+ab), 0],
                     [2*(bd+ac), 2*(cd-ab), aa+dd-bb-cc, 0],
                     [0, 0, 0, 1]])
```
```python
view = structure.plot3d()
view
```
```python
zoom_out = 20  # higher = farther away
scale = np.eye(4) * zoom_out

# Rotate 90 degrees about the y-axis; the
# default seems to always be projected along z-axis
R = get_rotation_matrix((0, 1, 0), np.pi/2)

orientation = np.dot(
    scale, get_rotation_matrix((0, 1, 0), np.pi/2)
).ravel().tolist()

# This updates the nglWidget running live in the cell above
# view._camera_orientation does the inverse, and
# exports the current orientation if you are ever curious
view.control.orient(
    orientation
)
```
