### ISSUE TITLE
Float input in structure.repeat() does not work

### ISSUE THREAD

**Issue by prince-mathews** [pyiron/pyiron#791]
```
Project('.').create_structure('Ni', 'fcc', a).repeat(n_repeat)
```

On using a value of n_repeat = 5.0,  the function raises an error, but using an integer value works.

**Comment by jan-janssen** [comment]
I guess it is similar like an index for a list:
`[1, 2, 3, 4, 5, 6][n_repeat]`
It works with int but does not work with float. So to me that is a feature not a bug.

**Comment by samwaseda** [comment]
@prince-mathews actually indeed used an integer, but `GenericParameter` for `ScriptJob` for some reason changed it to a float when the job was executed in a different notebook. I guess a safer behavior for `repeat` is that it changes the value an integer internally and maybe we can issue a warning if float was inserted or if the value was not the same before and after the conversion.

**Comment by jan-janssen** [comment]
@samwaseda I guess a saver way would be to fix `GenericParameter` if that is where the error is coming from. Or even better use `inputlist` for the script job because that should already fix the issue.

**Comment by samwaseda** [comment]
I’m also okay with this solution. Then for now I’d like to include an error in `repeat` that will make the user understand that a float was inserted (because the error message that @prince-mathews got was absolutely impossible to understand). If someone could do it right away, it would be nice. Otherwise I’ll do it tonight when I’m at home.
