### ISSUE TITLE
more documentation

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#793]
Our documentation could be a bit better where it goes beyond mere API docs (which we have a good amount of).  That means
- [ ] consistent information on the website/FAQ.  @samwaseda is working on this in #779, but won't mind help at all.
- [ ] [High-level docs](https://www.joelonsoftware.com/2000/10/02/painless-functional-specifications-part-1-why-bother/) on the overall architecture, how do the modules interact, who is responsible for what, etc.
    - [ ] @jan-janssen Already sent me some slides on the architecture, so I'll have a look at that.  But I'm also thinking more specific issues, like
    - [ ] What is the layout of a job in HDF5, both in general and class-specific. e.g. are input parameters always in a `input` group or named after their corresponding input files for the code.  What are some tools to check HDF5 files outside pyiron?
    - [ ] How to update resources, where put to what, if there's multiple folders which take priority, etc. (Am looking into this right now)
- [ ] The website could be shinier, e.g.
    - [ ] underscore main points of pyiron (job management, interactivity) more pronounced and less abstract.  Youtube videos have been mentioned.
    - [x] Do we want a website beyond what sphinx generates (i.e. appeals to non-devs, too)?

**Comment by ashtonmv** [comment]
>  The website could be shinier, e.g. underscore main points of pyiron (job management, interactivity) more pronounced and less abstract. Youtube videos have been mentioned.
>Do we want a website beyond what sphinx generates (i.e. appeals to non-devs, too)?

I would be happy to take a stab at this, unless someone else is already on top of it

**Comment by jan-janssen** [comment]
@sravankumarkb and @mostafajoulaian did a great job recently asking a lot of questions here on Github. Some related to bugs in pyiron and others mainly for clarification. I guess we can use these questions as a starting point to update the documentation: 

- how to change the energy convergence criteria "SPHInX" - https://github.com/pyiron/pyiron/issues/931
- No need to specify number of nodes? - https://github.com/pyiron/pyiron/issues/929
- Question about time limit of queues on cmti -  https://github.com/pyiron/pyiron/issues/927
- converting an ase structure into a pyiron structure - https://github.com/pyiron/pyiron/issues/924
- get final structure - https://github.com/pyiron/pyiron/issues/915
- loading project from path - https://github.com/pyiron/pyiron/issues/914

**Comment by sravankumarkb** [comment]
Thanks @jan-janssen for noticing! 😆

Can I suggest adding more examples and updating the current examples on the website?

The current examples are nice and there are lots of cool functions that new users can pick up from the examples.
But, for some layman/lazy users (like me!), they could be even further simplified and spoon-fed. Haha

For example, 
[https://wiki.fysik.dtu.dk/ase/python.html](url)
[https://wiki.fysik.dtu.dk/ase/ase/build/build.html?highlight=crystal](url)
[https://wiki.fysik.dtu.dk/ase/ase/calculators/vasp.html](url)

We can implement the same in our examples as well, for example, simply adding pictures below some of the cells with the .plot3d() function.
The same can be done for other functions by simplifying (or dumbing down :p) the examples, where we deal with just one concept/function at a time. For example, in the following nice example about data mining,

[https://pyiron.readthedocs.io/en/latest/source/notebooks/data_mining.html](url)
Instead of digging through the data on many jobs in sub projects, we can just illustrate how the user can store the data in a project table from just one job. then we can introduce the user to a complicated example as we have now.

The same strategy can be applied to explain the functionality of all the available functions. 

Yes, one can always do "?" in the notebook and try to figure out what the function does. But, it does not hurt to have a simple example on the website as well.

I would be more than happy to speak for a few mins (~5 min) about this in the pyiron meeting. I would be extremely interested in developing these simple examples and would very much welcome guidance on integrating these examples into the website.

Sorry for the long message. I wanted to get it off my chest for a while. 😆

**Comment by jan-janssen** [comment]
This issues is now open for more than three months, so I would prefer to close them to keep track of the topics we actually have time to work on right now. If we want to have a continuous discussion on this topic we could also open such a discussion in https://github.com/orgs/pyiron/teams/pyiron
