### ISSUE TITLE
Default pbc values: ASE vs pyiron

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#797]
Consider the following code:
```
from ase.atoms import Atoms as ASEAtoms
import numpy as np
basis = ASEAtoms("O", cell=np.eye(3)*10, positions=[[0, 0, 0]])
print(basis.pbc)
from pyiron.atomistics.structure.atoms import Atoms
basis = Atoms("O", cell=np.eye(3)*10, positions=[[0, 0, 0]])
print(basis.pbc)

>>> [False False False]
>>> [ True  True  True]
````

By default ase sets the pbc values to `False` while we set it to `True`. Since we are trying to be compatible with ASE (see https://github.com/pyiron/pyiron/pull/680) should we also change our default behaviour? If we do, some of our LAMMPS based notebooks will fail because LAMMPS does not count atoms outside a non-periodic box (see https://github.com/pyiron/pyiron/pull/796). On the other hand, since most of our calculations use `pbc`, it might be useful to switch this on by default. Thoughts?

**Comment by samwaseda** [comment]
I’m pretty sure that this is not the only one example where the ASE default is nonsense for pyiron. In this case I think it’s safe to assume that the pyiron community is happy to have `pbc=True` for the default behavior.

One possibility is to create a new function like `force_ase_default` which changes all pyiron default parameters to ASE parameters. This could be a relatively quick fix that we can implement now.

In the long run, I think we should think about introducing user-specific default values, since we’ve been having certain system specific parameters like k point mesh or energy cutoff radius in DFT, which maybe good for someone who always works with Aluminium but not for the ones who always work with Iron. And as we are trying to address broader audience, I guess classes like `Atoms` should be able to handle different default parameters depending on the scale and method the user is looking at anyway.

**Comment by sudarsan-surendralal** [comment]
Based on a detailed discussion with pyiron developers, it is decided that we use the ASE default unless we generate the structure from pyiron where we use the default pbc value of `True`
