### ISSUE TITLE
full_table=False doesn't set back the table size

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#828]
When I first implemented `pr.job_table(full_table=True)`, the table size was set back automatically as soon as `pr.job_table()` was called. Now I can see that `full_table` stays active, regardless of whether `pr.job_table()` or `pr.job_table(full_table=False)` was called, which sometimes makes a notebook slow.

**Comment by pmrv** [comment]
I'm not sure what your original solution was, but the way it is now, `pr.job_table()` has to set the pandas option and then return the table.  Since the option must be active when the result of the cell is shown by jupyter, i.e. after the cell finished executing, there's no way for pyiron code to disable the option again after the table is displayed.

**Comment by samwaseda** [comment]
I also don't think it's possible to set it back after the table is once shown, and neither particularly necessary. But I'd like pyiron to set it back when `pr.job_table(full_table=False)` is called.

And this was also the original behaviour. I don't think I had implemented something special - I essentially simply observed it was like that (although I vaguely remember that I thought it made sense).

**Comment by pmrv** [comment]
Ah, I misunderstood then.  Sure, that sounds like reasonable behaviour then and it should be an easy fix.
