### ISSUE TITLE
Function to check if all jobs in a "project" have finished

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#831]
Hi,
Is there a simple function to check if all jobs in a "project" have finished?
Currently, I am doing the following

`if (pr.get_jobs_status().finished)==len(pr.get_job_ids()): print ('done')`

I am wondering if there is a more elegant way to this. Thanks.

**Comment by jan-janssen** [comment]
```
df = pr.job_table()
if len(df[df.status != "finished"]) == 0: print("done") 
```
It is recommended to use the job_table which returns a pandas dataFrame

**Comment by pmrv** [comment]
We already have [wait_for_job](https://pyiron.readthedocs.io/en/latest/apidoc/pyiron.base.project.generic.html?highlight=wait#pyiron.base.project.generic.Project.wait_for_job).  Maybe we can just allow the first argument to be `None` and then wait for all or add something like
```python
def wait_for_jobs(self):
  for j in self.iter_jobs():
    self.wait_for_job(j)
```

I can see this being useful when turning notebooks into tests.

**Comment by jan-janssen** [comment]
As @sravankumarkb figured out the code above is dangerous as you open the HDF5 files of many jobs which can lead to cryptic errors. Instead it is recommended to just access the database rather than the HDF5 files. The functions would be something like: 

```
def wait_for_jobs(self, interval_in_s=5, max_iterations=100):
    for _ in range(max_iterations):
        df = self.job_table()
        if all(df.status.isin(["finished", "aborted", "not_converged"])):
            finished = True
            break
        time.sleep(interval_in_s)
    if not finished:
        raise ValueError("Maximum iterations reached, but the job was not finished.")
```

As we now have two issues about the same topic I close this one in the favour of https://github.com/pyiron/pyiron/issues/846
