### ISSUE TITLE
Behaviour of Group

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#891]
I have a group in SPHInX, in which I have:

```
job.input['KpointFolding']
>>> Group([3, 4, 28])
```

for which I get:

```
for i,k in enumerate(job.input['KpointFolding']):
    print(job.input['KpointFolding'][i], k)
>>> 3 0
>>> 4 1
>>> 28 2
```

What I was expecting to see was:

```
for i,k in enumerate(job.input['KpointFolding']):
    print(job.input['KpointFolding'][i], k)
>>> 3 3
>>> 4 4
>>> 28 28
```

Is this an expected behaviour?

**Comment by ashtonmv** [comment]
It's not expected (for me at least), but I believe it's not a problem with Group but rather has something to do with the reassigned `__iter__` method inherited from InputList:

```python
    def __iter__(self):

        reverse_indices = {i: k for k, i in self._indices.items()}

        for i in range(len(self)):
            yield reverse_indices.get(i, i)
```
If it does have to do with InputList, then @pmrv can probably say more about it than I can.

**Comment by pmrv** [comment]
It is, as in general `Group`/`InputList` can also have keys and so is a subclass of `Mapping` and for python says `iter()` of a `Mapping` must be over the keys of the container.  Changing it would probably mess up the generic implementations of the methods `InputList` inherits from `Mapping`.  In any case `.values()` always gives an iterator over the values in the list, so that to quickly coerce an `InputList` to a `list`, just use `list(input.values())` or `.to_builtin()`.

I agree it is annoying, especially since in this case a normal list would be enough for the k point folding.  We could change the initialization of the job so it stores a normal list under the key 'KpointFolding', then it behaves as expected.

**Comment by samwaseda** [comment]
Ok so since there's I guess no clear solution, I close this issue for now.
