### ISSUE TITLE
numpy DeprecationWarning: Creating an ndarray from ragged nested sequences

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#942]
The latest numpy raises annoying `VisibleDeprecationWarning` when you create an array from a list of lists with unequal sizes. This happens a lot with out `Neighbors` class

**Comment by samwaseda** [comment]
When does it happen? When you set `cutoff_radius`?

**Comment by sudarsan-surendralal** [comment]
> 
> 
> When does it happen? When you set `cutoff_radius`?

This happens when the atoms have an unequal number of neighbors within the specified cutoff (you can't reproduce this in bulk metals). Example:

```
from pyiron import Atoms
density = 1.0e-24  # g/A^3
n_mols = 27
mol_mass_water = 18.015 # g/mol

# Determining the supercell size size
mass = mol_mass_water * n_mols / 6.0231e23  # g
vol_h2o = mass / density # in A^3
a = vol_h2o ** (1./3.) # A

# Constructing the unitcell
n = int(round(n_mols ** (1. / 3.)))

dx = 0.7
r_O = [0, 0, 0]
r_H1 = [dx, dx, 0]
r_H2 = [-dx, dx, 0]
unit_cell = (a / n) * np.eye(3)
water = Atoms(elements=['H', 'H', 'O'],
                        positions=[r_H1, r_H2, r_O],
                        cell=unit_cell, pbc=True)
water.set_repeat([n, n, n])

water.get_neighbors(cutoff=1.0)

```

**Comment by samwaseda** [comment]
Okay that's what I was expecting. In my opinion, `cutoff` should not be used at all, or at least issues warnings (which is what happens currently), not only because the number of neighbours is not the same, but also because internally what counts is the number of neighbours for the tree algorithm. This means by setting the cutoff, in the best case we're losing information, and in the worst case the algorithm doesn't find all neighbours within the given cutoff range.

**Comment by sudarsan-surendralal** [comment]
> 
> 
> Okay that's what I was expecting. In my opinion, `cutoff` should not be used at all, or at least issues warnings (which is what happens currently), not only because the number of neighbours is not the same, but also because internally what counts is the number of neighbours for the tree algorithm. This means by setting the cutoff, in the best case we're losing information, and in the worst case the algorithm doesn't find all neighbours within the given cutoff range.

Not sure if I agree. The `ckdtree` algorithm can have both number of neighbors and cutoff distance as input (https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query.html) and as far as I see, there doesn't seem to be much of a difference wrt. efficiency (maybe I'm wrong). I don't think we lose any information from using `cutoff`. Besides, searching for neighbors based on cutoff distance is much more efficient and useful for molecules and surfaces where it's okay even if we don't find neighbors within a given radius (it's kinda the point).

**Comment by samwaseda** [comment]
Okay maybe there's a way for scipy to make it more efficient. But still I think a warning should be there, because the behaviour changes dramatically depending on whether it's numpy or list. Here's my suggestion: How about removing the conversion to numpy in `Neighbors`, which basically means `Neighbors` should become an object container and look like:

```
class Neighbors(object):
    def __init__(self):
        pass
```

And do instead in `get_neighbors`:

```
with warnings.catch_warnings(record=True) as w:
    neighbor_obj.indices = np.array(ind_lst)
    neighbor_obj.distances = np.array(d_lst)
    neighbor_obj.vecs = np.array(v_lst)
    if len(w)>0:
        warnings.warn('Number of neighbors is not the same; returned values are numpy arrays of lists')
```

This is not very different from what you did [here](https://github.com/pyiron/pyiron/pull/941), but I guess it's good because:
 - this doesn't have to change the filter (even though now I understand that it does not change the global filter, as you already indicated in the request)
 - issues a shorter but more comprehensive warning
 - makes it easier to understand which warnings are supposed to be intercepted with `catch_warnings` (because `catch_warnings` and numpy conversion are now close to each other)
 - reduces quite a number of lines.

What do you think?

**Comment by pmrv** [comment]
Only difference I'd make is using [named tuples](https://docs.python.org/3/library/collections.html?highlight=namedtuple#collections.namedtuple).

**Comment by sudarsan-surendralal** [comment]
Okay I agree but we still need to add `warnings.filter("always", np.VisibleDepreciationWarning)` to make sure that this particular warning is raised.
